eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka 
      preferIpAddress: true
      leaseExpirationDurationInSeconds: 20
spring:
   application:
      name: eurekaclientnewtwo